# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 484c3c39a30bd81d744284fcc99a66a585e74245049eaee5b1a711bff932117a0ec42f3f90d28e696e32091f6ac57f79109c8dd3d175e1d74d0baf412ef3d798

test:
  secret_key_base: bed38b59204ad3ff56ef9b184a774aeffc25a2e5e121d231632140d0ff71866c6f41614e39cffa8a06420c0e74a9644188502993d4d710aba949c18588a28739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
